### ISSUE TITLE
Command request mail: subscribe and unsubscribe to our various mailing lists

### ISSUE THREAD

**Issue by kristenmills** [rit-sse/slushbot#3]
- `/sse mail subscribe [email]`
- `/sse mail unsubscribe [email]`

Will subscribe or unsubscribe to mail chimp mailing list. Email is optional. Will do your slack email if nothing else is specified

**Comment by Omodi** [comment]
I'm glad I can add other people to the mailing list.

**Comment by kristenmills** [comment]
See I thought about that but then called it a nil issue because our current way of subscribing to the mailing list doesn't stop you from subscribing other people

**Comment by Omodi** [comment]
I guessed as much but it's still pretty funny to me.
